services:
  ai-studio-proxy:
    image: ghcr.io/muhammad-sho/ai-studio-proxy:latest
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    ports:
      - "${ADMIN_PORT:-9009}:${ADMIN_PORT:-9009}"
      - "${API_PORT:-9008}:${API_PORT:-9008}"
    volumes:
      - ./volumes:/data
